apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-pr-reviewer.fullname" . }}-config
  labels:
    {{- include "ai-pr-reviewer.labels" . | nindent 4 }}
data:
  AZURE_SERVICEBUS_QUEUE_NAME: {{ .Values.worker.env.azureServicebusQueueName | quote }}
  AZURE_OPENAI_API_VERSION: {{ .Values.worker.env.azureOpenaiApiVersion | quote }}
  SPRING_API_CALLBACK_URL: {{ include "ai-pr-reviewer.callbackUrl" . | quote }}
  DB_URL: {{ include "ai-pr-reviewer.dbUrl" . | quote }}
  DB_USERNAME: {{ include "ai-pr-reviewer.dbUsername" . | quote }}
