apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-pr-reviewer.fullname" . }}-config
  labels:
    {{- include "ai-pr-reviewer.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.api.env.awsRegion | quote }}
  OPENAI_MODEL: {{ .Values.worker.env.openaiModel | quote }}
  SPRING_API_CALLBACK_URL: {{ include "ai-pr-reviewer.callbackUrl" . | quote }}
  DB_URL: {{ include "ai-pr-reviewer.dbUrl" . | quote }}
  DB_USERNAME: {{ include "ai-pr-reviewer.dbUsername" . | quote }}
